# Generated by Django 3.0.5 on 2020-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anônimo', max_length=80, verbose_name='Nome(Opcional)')),
                ('data_envio', models.DateTimeField(auto_now=True, verbose_name='Comentado em')),
                ('conteudo', models.TextField(max_length=300, verbose_name='Como podemos ajudá-lo?')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'ordering': ('-data_envio',),
            },
        ),
    ]
