# Generated by Django 3.0.4 on 2020-04-03 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(default=datetime.datetime(2020, 4, 3, 17, 49, 57, 116098, tzinfo=utc), max_length=15, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_de_nascimento',
            field=models.DateField(auto_now=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
