# Generated by Django 3.0.4 on 2020-04-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200403_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cidade_usuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado_usuario',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_usuario',
            field=models.CharField(blank=True, max_length=5, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua_usuario',
            field=models.CharField(blank=True, max_length=70, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_de_nascimento',
            field=models.DateField(blank=True, verbose_name='Data de nascimento'),
        ),
    ]
