# Generated by Django 3.0.4 on 2020-04-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200403_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='endereco',
        ),
    ]
