# Generated by Django 3.0.4 on 2020-04-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200404_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='numero_usuario',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone para contato'),
        ),
    ]
