# Generated by Django 3.0.4 on 2020-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200408_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='unknow.png', upload_to='perfil', verbose_name='Foto de Perfil'),
        ),
    ]
