# Generated by Django 3.0.3 on 2020-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200408_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='perfil/unknow.png', upload_to='perfil', verbose_name='Foto de Perfil'),
        ),
    ]
