# Generated by Django 3.0.3 on 2020-04-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200425_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado_usuario',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
    ]
