# Generated by Django 3.0.4 on 2020-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0003_auto_20200318_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem',
            field=models.ImageField(upload_to='media/posts', verbose_name='Imagem'),
        ),
    ]
