# Generated by Django 3.0.4 on 2020-03-19 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicacoes', '0005_auto_20200319_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('caracteristicas', models.TextField(verbose_name='Caracaterísticas')),
                ('data_pub', models.DateTimeField(auto_now=True, verbose_name='Data de Publicação')),
                ('imagem', models.ImageField(upload_to='posts', verbose_name='Imagem')),
                ('estado', models.CharField(choices=[('P', 'Perdido'), ('PA', 'Para Adoção'), ('E', 'Encontrado')], max_length=15, verbose_name='Categoria')),
                ('sexo', models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], max_length=8, verbose_name='Sexo')),
                ('porte', models.CharField(choices=[('PE', 'Pequeno'), ('ME', 'Médio'), ('GR', 'Grande')], max_length=8, verbose_name='Porte')),
                ('vacinado', models.BooleanField(default=False, verbose_name='Vacinado')),
                ('vermifugado', models.BooleanField(default=False, verbose_name='Vermifugado')),
                ('castrado', models.BooleanField(default=False, verbose_name='Castrado')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('rua', models.CharField(max_length=70, verbose_name='Rua')),
                ('numero', models.CharField(max_length=5, verbose_name='Número')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_pub',),
            },
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
