# Generated by Django 3.0.4 on 2020-03-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0007_auto_20200319_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='estado',
            new_name='categoria',
        ),
    ]
