# Generated by Django 3.0.4 on 2020-04-03 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0009_auto_20200319_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='numero',
        ),
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(default=datetime.datetime(2020, 4, 3, 19, 5, 35, 422927, tzinfo=utc), max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
