# Generated by Django 3.0.5 on 2020-05-03 02:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0010_auto_20200403_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=80, verbose_name='Autor')),
                ('data_coment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Comentado em')),
                ('conteudo', models.TextField(max_length=300, verbose_name='Comentário')),
                ('aprovado', models.BooleanField(default=True)),
                ('avatar', models.ImageField(upload_to='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicacoes.Animal')),
            ],
        ),
    ]
