# Generated by Django 3.0.5 on 2020-05-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0011_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='avatar',
            field=models.CharField(max_length=50),
        ),
    ]
